# /// script
# requires-python = ">=3.10"
# dependencies = ["pandas", "numpy"]
# ///
"""Regenerate every generated document from the data in ../data/.

Outputs (all overwritten on each run — never hand-edit):

    README.md                        headline table + coverage line (between markers)
    ANALYSIS.md                      figures, regional tables, findings
    docs/methods/general-gradient.md the fallback rule, its validation, its caveats
    docs/tables/adult_mortality.md   the full per-census adult-mortality table
    docs/countries/<country>.md      per-country provenance pages
    docs/countries/README.md         index of the country pages

Keeps every data-derived number in the prose in sync with the CSVs, so the
documentation cannot drift from the data it describes. The narrative is fixed
here; the counts, tilts, and tables are computed. Run after the data or figures
change:

    uv run scripts/build_analysis.py

(or just run scripts/refresh.py, which chains data -> figures -> analysis).
"""

import re
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"
REGION_ORDER_NOTE = "(single survey)"
NEG = "−"  # true minus sign, matching the rest of the docs

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/build_analysis.py — do not edit by hand. -->\n"
)

# GNI per capita (current US$, Atlas method, ~2024) used only to print worked
# fallback values on the OG-family country pages. Update when re-basing.
WORKED_GNI = {"Philippines": 4450, "Indonesia": 5010, "Ethiopia": 1100}

# Countries that get a provenance page even without census-based content
# (the OG-Core family this library exists to serve).
OG_FAMILY = ["South Africa", "Philippines", "Indonesia", "Ethiopia", "Brazil"]

# Curated per-country provenance notes (narrative is fixed here by design —
# same rule as the rest of this generator). Keys are country names.
COUNTRY_NOTES = {
    "Brazil": [
        "**Adult mortality comes from IBGE's own open 2010 census sample "
        "microdata, not IPUMS.** The IPUMS mortality supplement for this census "
        "ships ~48% of the deaths the census itself reports, and the loss is "
        "concentrated in wealthy households — a wealth-skewed loss that would "
        "bias the tilt, not just add noise. The IPUMS rebuild is therefore "
        "marked `publish=False` in `scripts/build_adult_mortality.py` (with the "
        "evidence), and the committed rows come from IBGE.",
        "**The DHS fertility/child rows are old (1996).** Brazil's "
        "child-mortality gradient roughly halved between 1991 and 2010 (census "
        "series above); prefer `census_child_mortality.csv` for the child "
        "gradient and treat the 1996 DHS tilt as an upper bound.",
        "The census child-mortality series is published on two asset-index "
        "bases (`index` column): `full` (all assets each census offers) and "
        "`common` (only electricity/fridge/TV/radio/cars, comparable across "
        "1991/2000/2010). Use `full`; the 2010 common-index estimate collapses "
        "to two groups because nearly every household owned all four items.",
    ],
    "South Africa": [
        "Three censuses (2001, 2007, 2011) plus DHS 2016. The 2011 census "
        "links only ~9% of death records to asset data (`linked_share`), so "
        "its *levels* are meaningless — but the linked deaths match the "
        "unlinked on province, urban/rural, sex, and age, so the tilt is "
        "unbiased.",
        "A per-sample lesson recorded in the pipeline: IPUMS `AUTOS` code 7 "
        "means \"has a car, count unspecified\", not seven cars; treating it "
        "as a count materially changed the 2011 tilt (−1.14 → −0.80).",
        "The DHS 2016 child-mortality quintile cells are visibly noisy "
        "(non-monotonic top quintiles) — small death counts in a "
        "low-mortality survey. The tilt is usable; individual cells are not.",
        "South Africa's own census measurement (−0.80) should be used over "
        "the general gradient's prediction (−0.83).",
    ],
    "Ethiopia": [
        "The 2007 census asks assets and mortality of the long-form 20% "
        "subsample only; its weights already inflate to national totals — do "
        "not re-scale. 46% of persons hold no assets, so the asset "
        "distribution supports only three wealth groups (`groups` column).",
        "Ethiopia is the flattest adult gradient in the library (45q15 tilt "
        "≈ +0.09, i.e. no protective wealth gradient), and at 30+ the "
        "measured gradient turns positive — see the older-age reversal "
        "discussion in the general-gradient page before using the older "
        "bands.",
        "For fertility use the **2016 full EDHS** — the 2019 mini-DHS has no "
        "fertility module.",
    ],
    "Philippines": [
        "No census household-deaths module is available, so there is no "
        "measured adult-mortality gradient; use the general gradient "
        "(worked value below). The DHS rows (NDHS 2022) cover fertility and "
        "child mortality directly.",
    ],
    "Indonesia": [
        "No census household-deaths module is available, so there is no "
        "measured adult-mortality gradient; use the general gradient "
        "(worked value below). The DHS rows (IDHS 2017) cover fertility and "
        "child mortality directly.",
        "Indonesia is the canonical tempo case: its TFR-by-wealth gradient "
        "is nearly flat while adolescent childbearing differs ~8× between "
        "poorest and richest quintiles — the gradient lives in the age "
        "pattern, not the total.",
    ],
    "Benin": [
        "The 2013 census records deaths since 1 January 2012 (~16 months to "
        "the May census) — fine for tilts, not levels. Capture against the "
        "national death count is ~35%, wealth-uniform, so it cancels out of "
        "the tilt.",
    ],
    "Malawi": [
        "Two censuses (1998, 2008) make Malawi the worked example that the "
        "gradient steepens as income rises: the measured 45q15 tilt moved "
        "from −0.02 to −0.28 as income per head roughly doubled, within 0.07 "
        "of what the general gradient's income rule predicts.",
    ],
}


def fmt(x):
    return f"{NEG}{abs(x):.2f}" if x < 0 else f"{x:.2f}"


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def load():
    lib = pd.read_csv(DATA / "gradient_library.csv")
    latest = pd.read_csv(DATA / "gradient_library_latest.csv").merge(
        pd.read_csv(DATA / "dhs_regions.csv"), on="country", how="left"
    )
    return lib, latest


def headline(latest, ind):
    l = latest[latest["indicator"] == ind]
    return {
        "n": l["country"].nunique(),
        "med": l["slope"].median(),
        "q25": l["slope"].quantile(0.25),
        "q75": l["slope"].quantile(0.75),
        "ratio": l["ratio"].median(),
    }


def census_child_mortality():
    """The census child-mortality series, on its published (full-index) basis."""
    p = DATA / "census_child_mortality.csv"
    if not p.exists():
        return None
    d = pd.read_csv(p)
    f = d[(d["index"] == "full") & (d["measure"] == "prop_dead_2529")]
    c = d[(d["index"] == "common") & (d["measure"] == "prop_dead_2529")]
    if not len(f):
        return None
    rows = "\n".join(
        f"| {int(r.year)} | {r.groups} | {fmt(r.slope)} | {r.ratio:.2f} | "
        f"{r.q1 * 100:.1f}% |"
        for _, r in f.sort_values("year").iterrows())
    ff, cc = f.sort_values("year"), c.sort_values("year")
    # the row carrying a DHS cross-check, and how close it landed
    vrow = f[f["dhs_check"].astype(str).str.len() > 0]
    vtilt = float(vrow["slope"].iloc[0]) if len(vrow) else float("nan")
    chk = str(vrow["dhs_check"].iloc[0]) if len(vrow) else ""
    vref = float(chk.split()[-1]) if chk else float("nan")
    vsurvey = chk.split(" U5MR")[0] if chk else ""
    return {"rows": rows, "n": len(f), "vtilt": vtilt, "vdiff": abs(vtilt - vref),
            "vsurvey": vsurvey, "vref": vref,
            "y0": int(ff.year.iloc[0]), "y1": int(ff.year.iloc[-1]),
            "t0": ff.slope.iloc[0], "t1": ff.slope.iloc[-1],
            "chg_full": ff.slope.iloc[-1] - ff.slope.iloc[0],
            "chg_common": (cc.slope.iloc[-1] - cc.slope.iloc[0]) if len(cc) > 1 else float("nan"),
            "check": next((x for x in f["dhs_check"] if isinstance(x, str) and x), ""),
            "df": d}


def general_gradient():
    """The fallback rule and its validation, read from data/ so it cannot drift."""
    p = DATA / "general_gradient.csv"
    if not p.exists():
        return None
    g = pd.read_csv(p)
    d = {f"{r['component']}.{r['key']}": r["value"] for _, r in g.iterrows()}
    d["_ages"] = [(r["key"], r["value"]) for _, r in
                  g[g["component"] == "age_offset"].iterrows()]
    return d


def imr_vs_u5mr(lib):
    """How much steeper the U5MR proxy is than the infant series it stands in for."""
    p = lib.pivot_table(index=["country", "year"], columns="indicator",
                        values="slope")
    if "IMR" not in p.columns:
        return None
    p = p[["IMR", "U5MR"]].dropna()
    if not len(p):
        return None
    d = p["IMR"] - p["U5MR"]
    return {"n": len(p), "med_imr": p["IMR"].median(), "med_u5": p["U5MR"].median(),
            "med_diff": d.median(), "share_flatter": (d > 0).mean(),
            "r": p["IMR"].corr(p["U5MR"]),
            "worst": d.abs().idxmax(), "worst_gap": d.abs().max()}


def amr_headline():
    """One 45q15 observation per census: the 'all' row, else the sex mean."""
    p = DATA / "adult_mortality_gradients.csv"
    if not p.exists():
        return None
    q = pd.read_csv(p)
    q = q[q["measure"] == "45q15"]
    if not len(q):
        return None
    obs, ratios = [], []
    for _, g in q.groupby(["country", "year"]):
        a = g[g["sex"] == "all"]
        src = a if len(a) else g[g["sex"].isin(["male", "female"])]
        obs.append(float(src["slope"].mean()))
        ratios.append(float(src["ratio"].mean()))
    s, r = pd.Series(obs), pd.Series(ratios)
    return {"n": q["country"].nunique(), "censuses": len(obs), "med": s.median(),
            "q25": s.quantile(0.25), "q75": s.quantile(0.75), "ratio": r.median()}


def region_table(latest, ind):
    l = latest[latest["indicator"] == ind]
    g = (
        l.groupby("region")
        .agg(
            n=("country", "nunique"),
            med=("slope", "median"),
            q25=("slope", lambda s: s.quantile(0.25)),
            q75=("slope", lambda s: s.quantile(0.75)),
            ratio=("ratio", "median"),
        )
        .sort_values("med")
    )
    rows = []
    for rgn, r in g.iterrows():
        iqr = REGION_ORDER_NOTE if r["n"] == 1 else f"{fmt(r['q25'])} to {fmt(r['q75'])}"
        rows.append(
            f"| {rgn} | {int(r['n'])} | {fmt(r['med'])} | {iqr} | {r['ratio']:.2f} |"
        )
    return "\n".join(rows)


def sa(latest, ind):
    row = latest[(latest["indicator"] == ind) & (latest["country"] == "South Africa")]
    if not len(row):
        return None
    return {"slope": row["slope"].iloc[0], "ratio": row["ratio"].iloc[0], "year": int(row["year"].iloc[0])}


def replace_between(text, start, end, new):
    a, b = text.index(start) + len(start), text.index(end)
    return text[:a] + "\n" + new + "\n" + text[b:]


def amr_table_rows(amr):
    out = ""
    for _, r in amr.iterrows():
        out += (
            f"| {r['country']} | {r['year']} | {r['sex']} | {r['age_lo']}–{r['age_hi']} "
            f"| {r['measure']} | {fmt(r['slope'])} | {r['ratio']:.2f} | {r['n_deaths']:,} "
            f"| {r.get('linked_share', 1.0):.0%} |\n"
        )
    return out


def write_general_gradient_page(amr):
    """docs/methods/general-gradient.md — fully generated (its numbers compute)."""
    gg = general_gradient() or {}
    gg_a = gg.get("income_rule.intercept", float("nan"))
    gg_b = gg.get("income_rule.slope_ln_gni", float("nan"))
    gg_r = gg.get("income_rule.r", float("nan"))
    gg_n = gg.get("income_rule.n_censuses", float("nan"))
    gg_sd = gg.get("income_rule.residual_sd", float("nan"))
    gg_dbl = gg_b * 0.6931  # effect of doubling income
    gg_med = gg.get("fallback.pooled_median_tilt", float("nan"))
    gg_mae_c = gg.get("validation.loo_mae_rule_constant", float("nan"))
    gg_mae_i = gg.get("validation.loo_mae_rule_income", float("nan"))
    gg_mae_r = gg.get("validation.loo_mae_rule_region", float("nan"))
    gg_agemae = gg.get("validation.age_offset_mae", float("nan"))
    mw = amr[(amr.country == "Malawi") & (amr.measure == "45q15")
             & (amr.sex == "all")].sort_values("year")
    gg_mw0 = float(mw.slope.iloc[0]) if len(mw) > 1 else float("nan")
    gg_mw1 = float(mw.slope.iloc[-1]) if len(mw) > 1 else float("nan")
    gg_mwerr = abs(gg_mw0 - (gg_a + gg_b * np.log(290))) if len(mw) > 1 else float("nan")
    gg_bsign, gg_babs = ("+" if gg_b >= 0 else NEG), abs(gg_b)
    gg_agerows = "\n".join(
        f"| {b} | {fmt(v)} | {'least trustworthy' if b in ('45-59', '60-74') else ''} |"
        for b, v in gg.get("_ages", []))
    n_cens = amr.groupby(["country", "year"]).ngroups
    doc = f"""{GENERATED_BANNER}# The general gradient: adult mortality when a country has no measurement

Most countries have no measured adult-mortality gradient. The library therefore
publishes a fallback in
[`data/general_gradient.csv`](../../data/general_gradient.csv), and the rule for
using it is simple: **a country with its own measurement should always prefer
it; the general gradient is for everyone else.** (Per-country routes are on the
[country pages](../countries/).)

The steepness of the gradient tracks how rich the country is:

    tilt(45q15) = {gg_a:.3f} {gg_bsign} {gg_babs:.3f} × ln(GNI per capita, current US$)

with r = {fmt(gg_r)} across {gg_n:.0f} censuses and a 1 SD band of
±{gg_sd:.2f}. Doubling income per head steepens the gradient by about
{fmt(gg_dbl)}.

That rule was chosen by competition, not assertion. Three candidates were each
judged by leaving one census out of the fit and predicting it — the honest test,
because a country using the fallback is by definition not in the fit:

| Candidate rule | Mean absolute error |
|---|---|
| One tilt for every country (the pooled median, {fmt(gg_med)}) | {gg_mae_c:.3f} |
| **Read it off national income** | **{gg_mae_i:.3f}** |
| The country's regional median | {gg_mae_r:.3f} |

Income is wrong by less than half as much as a single global number, and a third
less than regional medians. So there is a general gradient, and income — not
region — is what it tracks. It is also most accurate in the middle-income range
where the countries needing it actually sit, and it reproduces South Africa's own
census measurement to within a rounding error.

## Spreading the tilt across age bands

To spread the summary tilt across age bands, which is what ogcore's
`mort_gradient` accepts, add these pooled offsets:

| Age band | Offset to add | |
|---|---|---|
{gg_agerows}

Applying an offset this way reproduces a country's own measured band tilt to a
median ±{gg_agemae:.2f}, so the age shape is a good deal coarser than the level.

**The 45–59 and 60–74 offsets are the least trustworthy numbers in this file.**
They are positive because in the poorest countries measured mortality rises with
wealth at older ages, and that may not be real — see the next section. A model
that only needs working-age mortality should prefer the 15–29 and 30–44 offsets
and treat the older ones as an upper bound on flatness.

**Do not hold a low-income country's tilt fixed across a long transition.** As
income rises the gradient should be expected to steepen toward the upper-middle
values in this table — Malawi is the worked case, its own measured tilt moving
from {fmt(gg_mw0)} to {fmt(gg_mw1)} as income per head roughly doubled between
its 1998 and 2008 censuses, within {gg_mwerr:.2f} of what the rule predicts.

The rule is fitted between about $200 and $10,000 of GNI per head, which is the
range this library covers by design: every source it draws on is a
developing-country instrument. Do not extrapolate it to high-income countries.
Of the {n_cens} censuses behind it, eleven are African and none Asian, so its
predictions for Asian countries are extrapolation.

## The reversal at older ages, and why HIV does not explain it

In the poorest countries the gradient is flat, and at older ages it turns
positive: measured mortality is *higher* in wealthier households in Ethiopia
2007, Uganda 2002, South Sudan 2008 and Mozambique 2007. Where almost everyone
is poor, the top asset group is barely better protected, and deaths are
infectious and maternal rather than the socially graded chronic diseases of
middle income. Against that, a frail elderly relative often moves into a
better-off household before dying, which records the death against that
household's wealth.

Independent evidence now favours a reporting explanation for at least part of
it. In DHS sibling histories — a different source, also relying on a
household's recall of deaths — poorer and less educated respondents report
*fewer* siblings than richer ones despite having far more children of their own,
and the deficit grows the further back they are asked to recall. Under-reporting
of deaths by poorer respondents flattens or reverses a measured gradient in
exactly this way. That does not prove the census reversal is artefactual, but it
makes it the more likely reading, and it is why the older-age offsets above
carry a warning.

HIV does not explain the pattern: excluding South Africa, the correlation
between the tilt and HIV prevalence is +0.00, Lesotho has the set's highest
prevalence with a solidly negative tilt, and the reversal is strongest at
60–74, where HIV mortality is rare.
"""
    (DOCS / "methods" / "general-gradient.md").write_text(doc)


def write_adult_table_page(amr):
    """docs/tables/adult_mortality.md — the full per-census table + column notes."""
    doc = f"""{GENERATED_BANNER}# Adult-mortality gradients: the full per-census table

Every published estimate in
[`data/adult_mortality_gradients.csv`](../../data/adult_mortality_gradients.csv),
one row per country × census × sex × age band. Method:
[census household-deaths modules](../methods/adult-mortality.md); fallback for
unmeasured countries: [the general gradient](../methods/general-gradient.md).

## What the columns mean

`linked` is the share of the census's death records that reached estimation.
Where it is well below 1 (South Africa 2011), rate *levels* are meaningless but
the tilt is unbiased — the linked deaths' composition matches the unlinked on
province, urban/rural, sex, and age.

Every sample here passed a completeness check: the supplementary per-death file
is compared, *within each wealth group*, against the same households' own
reported death counts (`MORTNUM`). Even record loss cancels out of a tilt;
wealth-skewed loss does not. Three samples failed and are deliberately absent —
the IPUMS mortality supplement for Brazil 2010 (holds 48% of the deaths the
census itself reports, with the loss concentrated in wealthy households; the
Brazil rows below come from IBGE's own microdata instead), Nepal 2001, and El
Salvador 2007. Their evidence is recorded in
`scripts/build_adult_mortality.py`.

Ranking: household asset index (see the
[method page](../methods/adult-mortality.md) for the income-vs-assets
validation and the build pipeline; asset components vary by census and are
recorded in `scripts/build_adult_mortality.py`).

| Country | Year | Sex | Ages | Measure | Tilt | Poorest/richest | Death records | Linked |
|---|---|---|---|---|---|---|---|---|
{amr_table_rows(amr)}"""
    (DOCS / "tables" / "adult_mortality.md").write_text(doc)


def country_dhs_block(latest, country):
    rows = latest[latest["country"] == country]
    if not len(rows):
        return ""
    out = ("## DHS survey gradients (fertility & child mortality)\n\n"
           "From [`data/gradient_library_latest.csv`](../../data/gradient_library_latest.csv)"
           " (most recent survey; the full survey history is in"
           " `gradient_library.csv`).\n\n"
           "| Indicator | Survey year | Tilt | Poorest/richest | Q1 … Q5 |\n"
           "|---|---|---|---|---|\n")
    order = {"TFR": 0, "IMR": 1, "U5MR": 2}
    for _, r in rows.sort_values("indicator", key=lambda s: s.map(order)).iterrows():
        qs = " / ".join("" if pd.isna(r[q]) else f"{r[q]:g}" for q in ["q1", "q2", "q3", "q4", "q5"])
        out += (f"| {r['indicator']} | {int(r['year'])} | **{fmt(r['slope'])}** "
                f"| {r['ratio']:.2f} | {qs} |\n")
    out += ("\nSource: DHS Program indicator API (wealth-quintile breakdown); "
            "tilt = OLS slope of ln(rate) on wealth rank.\n")
    return out


def country_amr_block(amr, country):
    rows = amr[amr["country"] == country]
    if not len(rows):
        return ""
    srcs = sorted(rows["source"].dropna().unique())
    censuses = sorted(rows["year"].unique())
    meta = []
    for y in censuses:
        g = rows[rows["year"] == y]
        meta.append(
            f"- **{y} census** — {int(g['n_deaths'].sum()):,} death records across "
            f"published rows; {int(g['groups'].iloc[0])} wealth groups; ranking: "
            f"{g['ranking'].iloc[0].replace('_', ' ')}; linked share "
            f"{g['linked_share'].iloc[0]:.0%}.")
    out = ("## Adult mortality (census household-deaths modules)\n\n"
           "From [`data/adult_mortality_gradients.csv`](../../data/adult_mortality_gradients.csv)."
           " Households ranked by asset index; see the"
           " [method page](../methods/adult-mortality.md).\n\n"
           + "\n".join(meta) + "\n\n"
           "| Year | Sex | Ages | Measure | Tilt | Poorest/richest | Deaths |\n"
           "|---|---|---|---|---|---|---|\n")
    for _, r in rows.iterrows():
        out += (f"| {r['year']} | {r['sex']} | {r['age_lo']}–{r['age_hi']} | {r['measure']} "
                f"| **{fmt(r['slope'])}** | {r['ratio']:.2f} | {r['n_deaths']:,} |\n")
    out += "\nSource: " + "; ".join(srcs) + ".\n"
    return out


def country_ccm_block(ccm_df, country):
    if ccm_df is None:
        return ""
    rows = ccm_df[(ccm_df["country"] == country) & (ccm_df["measure"] == "prop_dead_2529")]
    if not len(rows):
        return ""
    out = ("## Child mortality from censuses\n\n"
           "From [`data/census_child_mortality.csv`](../../data/census_child_mortality.csv)."
           " The measure is the proportion of children ever born who have died"
           " (Brass indirect, mothers 25–29) — a cumulative proportion whose"
           " *levels* must not be pooled with DHS U5MR; only the tilt is"
           " comparable.\n\n"
           "| Census | Index | Groups | Tilt | Poorest/richest |\n"
           "|---|---|---|---|---|\n")
    for _, r in rows.sort_values(["year", "index"]).iterrows():
        out += (f"| {int(r['year'])} | {r['index']} | {r['groups']} | **{fmt(r['slope'])}** "
                f"| {r['ratio']:.2f} |\n")
    chk = rows[rows["dhs_check"].astype(str).str.len() > 0]
    if len(chk):
        out += f"\nCross-check: {chk['dhs_check'].iloc[0]}.\n"
    out += "\nAsset components per census are recorded in the `asset_vars` column.\n"
    return out


def country_fallback_block(country, amr):
    gg = general_gradient() or {}
    a = gg.get("income_rule.intercept", float("nan"))
    b = gg.get("income_rule.slope_ln_gni", float("nan"))
    sd = gg.get("income_rule.residual_sd", float("nan"))
    has_own = country in set(amr["country"])
    if has_own:
        return ("## Adult-mortality route for calibration\n\n"
                "This country has its **own census measurement — use it** (rows "
                "above), not the general gradient.\n")
    if country in WORKED_GNI:
        gni = WORKED_GNI[country]
        tilt = a + b * np.log(gni)
        return (f"## Adult-mortality route for calibration\n\n"
                f"No census household-deaths module exists, so use the "
                f"[general gradient](../methods/general-gradient.md): at GNI per "
                f"capita ≈ ${gni:,} (~2024), predicted tilt(45q15) = "
                f"**{fmt(tilt)}** ± {sd:.2f}, spread across age bands with the "
                f"by-age offsets in `data/general_gradient.csv`.\n")
    return ("## Adult-mortality route for calibration\n\n"
            "No census measurement; use the "
            "[general gradient](../methods/general-gradient.md) at the "
            "country's GNI per capita.\n")


def write_country_pages(latest, amr, ccm):
    ccm_df = ccm["df"] if ccm else None
    countries = sorted(set(amr["country"]) | set(OG_FAMILY)
                       | (set(ccm_df["country"]) if ccm_df is not None else set()))
    index_rows = []
    for c in countries:
        blocks = [country_dhs_block(latest, c),
                  country_ccm_block(ccm_df, c),
                  country_amr_block(amr, c),
                  country_fallback_block(c, amr)]
        notes = COUNTRY_NOTES.get(c, [])
        note_txt = ("## Provenance notes\n\n" + "\n".join(f"- {n}" for n in notes) + "\n") if notes else ""
        doc = (f"{GENERATED_BANNER}# {c}\n\n"
               f"Everything this library holds for {c}, with provenance. "
               f"Tilt = OLS slope of ln(rate) on wealth rank 0–1; ogcore "
               f"consumes tilt ÷ 100 (see [AGENTS.md](../../AGENTS.md)).\n\n"
               + "".join(b + "\n" for b in blocks if b) + note_txt)
        (DOCS / "countries" / f"{slug(c)}.md").write_text(doc)
        what = []
        if len(latest[latest["country"] == c]):
            what.append("DHS")
        if ccm_df is not None and len(ccm_df[ccm_df["country"] == c]):
            what.append("census child")
        if len(amr[amr["country"] == c]):
            what.append("census adult")
        index_rows.append(f"| [{c}]({slug(c)}.md) | {', '.join(what) or 'general gradient only'} |")
    idx = (f"{GENERATED_BANNER}# Country provenance pages\n\n"
           "One page per country with census-based content or OG-Core family "
           "membership: every estimate the library holds for it, where each "
           "number comes from, and the recommended calibration route.\n\n"
           "| Country | Instruments |\n|---|---|\n" + "\n".join(index_rows) + "\n\n"
           "**Any other country:** take its row in "
           "[`data/gradient_library_latest.csv`](../../data/gradient_library_latest.csv) "
           "for fertility/infant mortality (or the regional median in "
           "[ANALYSIS.md](../../ANALYSIS.md) if it has no survey), and the "
           "[general gradient](../methods/general-gradient.md) for adult "
           "mortality. Precedence rules: [AGENTS.md](../../AGENTS.md).\n")
    (DOCS / "countries" / "README.md").write_text(idx)
    return countries


def main():
    lib, latest = load()
    tfr, u5, imr = headline(latest, "TFR"), headline(latest, "U5MR"), headline(latest, "IMR")
    # lib has one row per country x year x indicator; a "survey" is a country-year
    n_surveys = lib.groupby(["country", "year"]).ngroups
    n_obs = len(lib)
    n_countries = latest["country"].nunique()

    # --- README headline table (between markers) ---
    readme_path = ROOT / "README.md"
    readme = readme_path.read_text()
    table = (
        "| Margin | Countries | Median tilt | IQR | Median poorest/richest ratio |\n"
        "|---|---|---|---|---|\n"
        f"| Fertility (TFR) | {tfr['n']} | **{fmt(tfr['med'])}** | "
        f"{fmt(tfr['q25'])} to {fmt(tfr['q75'])} | {tfr['ratio']:.2f} |\n"
        f"| Infant mortality | {imr['n']} | **{fmt(imr['med'])}** | "
        f"{fmt(imr['q25'])} to {fmt(imr['q75'])} | {imr['ratio']:.2f} |\n"
        f"| Under-5 mortality (fallback) | {u5['n']} | **{fmt(u5['med'])}** | "
        f"{fmt(u5['q25'])} to {fmt(u5['q75'])} | {u5['ratio']:.2f} |"
    )
    amr_h = amr_headline()
    if amr_h:
        table += (
            f"\n| Adult mortality (45q15) | {amr_h['n']} | **{fmt(amr_h['med'])}** | "
            f"{fmt(amr_h['q25'])} to {fmt(amr_h['q75'])} | {amr_h['ratio']:.2f} |"
        )
    readme = replace_between(
        readme,
        "<!-- AUTO-GENERATED by scripts/build_analysis.py — do not edit by hand -->",
        "<!-- END AUTO-GENERATED -->",
        table,
    )
    # keep the coverage parenthetical in step with the data too
    readme = re.sub(r"\d[\d,]* surveys, \d+ countries",
                    f"{n_surveys:,} surveys, {n_countries} countries", readme)
    readme_path.write_text(readme)
    print(f"updated README headline table ({n_surveys} surveys, {n_countries} countries)")

    # --- ANALYSIS.md (fully generated) ---
    sa_t, sa_u = sa(latest, "TFR"), sa(latest, "U5MR")
    cmp_ = imr_vs_u5mr(lib)
    doc = f"""# The gradient library, in figures

Documentation of the data in this repo. **This file is generated** by
[`scripts/build_analysis.py`](scripts/build_analysis.py) from the CSVs in
[`data/`](data/); every number below is computed from the data, not hand-typed,
so it cannot drift. Figures come from
[`scripts/make_figures.py`](scripts/make_figures.py) and live in
[`figures/`](figures/). Regenerate everything with `uv run scripts/refresh.py`.

Method pages, the full adult-mortality table, and per-country provenance pages
live under [`docs/`](docs/) — see the map in the [README](README.md).

South Africa is highlighted throughout as the worked example; pass
`--highlight "<country>"` to `make_figures.py` to feature any other.

The **tilt** summarizing each survey is the OLS slope of ln(rate) on wealth-rank
percentile midpoints (quintiles at the 10th…90th percentile) — the same log scale
OG-Core's income-group demographics consume. Negative means the poor have higher
rates; a tilt of {fmt(tfr['med'])} puts the poorest decile's rate at about
e^({abs(tfr['med']):.2f}×0.8) ≈ {2.718281828 ** (abs(tfr['med']) * 0.8):.1f}× the richest decile's.

Coverage: **{n_surveys} surveys with complete wealth quintets across
{n_countries} countries**, giving {n_obs} country-survey-margin tilts (most
recent survey per country used for the library view below).

## Every country, individually

Nearly every line slopes down: the wealth gradient in fertility is close to
universal. South Africa is both low-fertility and mild-gradient (tilt
{fmt(sa_t['slope'])} in {sa_t['year']}, vs the pooled median of {fmt(tfr['med'])}).

![Fertility (TFR) by household wealth rank, one line per country](figures/fig1_tfr_gradients.png)

The same universal direction holds for child mortality, with wider spread across
countries. South Africa's non-monotonic top quintiles reflect the small
child-mortality samples in its {sa_u['year']} survey.

![Under-5 mortality by household wealth rank, one line per country](figures/fig2_u5mr_gradients.png)

### Use infant mortality, not under-5, for `infmort_gradient`

The library carries both. They are not interchangeable, and the difference runs
one way: across the {cmp_['n']} surveys that report both by wealth quintile, the
under-5 tilt is steeper than the infant tilt by a median
{abs(cmp_['med_diff']):.2f}, and it is steeper in {cmp_['share_flatter']:.0%} of
them. The two are strongly correlated (r = {cmp_['r']:.2f}), so the shape of the
story is the same — but the level is not, and the gap reaches
{cmp_['worst_gap']:.2f} ({cmp_['worst'][0]} {cmp_['worst'][1]}).

The reason is what under-5 mortality includes. Deaths between ages 1 and 4 are
dominated by diarrhoea, malaria, and malnutrition, which wealth protects against
strongly; infant deaths lean toward prematurity and birth complications, which it
protects against much less. Using under-5 as the infant proxy therefore imports
the steeper child-mortality gradient into a parameter meant to describe infants.
Prefer `indicator == "IMR"`, and fall back to `"U5MR"` only for the surveys that
report no infant quintiles.

## Grouped by region

Each dot is a country's most recent survey; the bar marks the regional
interquartile range and the tick marks the median. Latin America has the steepest
gradients; Sub-Saharan Africa sits mid-range; South Africa is milder than its
region's median on fertility.

![Distribution of gradient tilts by region](figures/fig3_slopes_by_region.png)

**Fertility (TFR) tilt by region**

| Region | Countries | Median tilt | IQR | Median poorest/richest ratio |
|---|---|---|---|---|
{region_table(latest, "TFR")}

**Infant mortality tilt by region** — the series `infmort_gradient` should use

| Region | Countries | Median tilt | IQR | Median poorest/richest ratio |
|---|---|---|---|---|
{region_table(latest, "IMR")}

**Under-5 mortality tilt by region** — the fallback, and steeper (see below)

| Region | Countries | Median tilt | IQR | Median poorest/richest ratio |
|---|---|---|---|---|
{region_table(latest, "U5MR")}

## Stability over survey years

All {n_obs} country-survey-margin tilts plotted by fieldwork year, with a
rolling median. The
pooled gradient is nearly flat across three and a half decades — wealth gradients
are a stable structural feature, not an eroding one, so a borrowed gradient is not
a decaying quantity. South Africa's own fertility gradient flattened between its
1998 and {sa_t['year']} surveys.

![Gradient tilts across survey years](figures/fig4_slopes_over_time.png)

**Stable across countries is not the same as stable within one.** The flat line
above is a pooled median over many countries; a single fast-developing country
can move a long way underneath it. Brazil is the worked case — see the census
series below, where its child-mortality gradient roughly halves in twenty years.
Read the pooled stability as "a borrowed gradient does not decay", not as "a
country's own gradient will not change".
"""

    ccm = census_child_mortality()
    if ccm:
        doc += f"""
## Child mortality from censuses, and Brazil's twenty-year trend

The DHS child-mortality gradients above are one survey per country, and for some
countries that survey is old — Brazil's only usable DHS is 1996. Censuses ask
every mother how many children she has borne and how many are still alive, so
the household asset index already used for adult mortality yields a
child-mortality gradient for any census year, including years no survey covers.
These rows live in
[`data/census_child_mortality.csv`](data/census_child_mortality.csv).

The measure is the proportion of children ever born who have died — the classic
Brass indirect indicator, for mothers aged 25–29. It is cumulative rather than a
period rate, so **its levels are not comparable to DHS U5MR levels and must not
be pooled with them.** Only the tilt is comparable.

That comparability was tested rather than assumed. Brazil's 2000 census sits four
years after its 1996 DHS, and the two agree to {ccm['vdiff']:.3f}: the census
gives {fmt(ccm['vtilt'])} where the {ccm['vsurvey']} U5MR gradient is
{fmt(ccm['vref'])}. Two independent sources, with different measures and
different wealth rankings, landing on the same number.

| Census | Groups | Tilt | Poorest/richest | Poorest group's children dead |
|---|---|---|---|---|
{ccm['rows']}

**Brazil's child-mortality gradient roughly halved**, from {fmt(ccm['t0'])} in
{ccm['y0']} to {fmt(ccm['t1'])} in {ccm['y1']}. Child mortality fell in every
group, but proportionally faster among the poor, and the poorest-to-richest ratio
narrowed from 4.4× to 2.1×.

That is a real change, not an artefact of the asset index growing richer over
time (1991 offers four asset variables, 2010 offers ten). Re-estimating every
census on only the assets common to all three — electricity, fridge, TV, radio
and cars — the flattening is *larger*, {fmt(ccm['chg_common'])} against
{fmt(ccm['chg_full'])} on the full index. Both variants are published, tagged by
the `index` column; use `index == "full"`, which supports more wealth groups. The
common-index 2010 estimate collapses to two groups, because by then nearly every
Brazilian household owned all four items — a warning that simple durable-goods
indices stop discriminating as a country gets richer.

**For calibration:** the library's Brazil DHS row is a 1996 tilt of −1.46, and by
2010 the value was near {fmt(ccm['t1'])}. A present-day Brazilian calibration
using the DHS row overstates the child-mortality gradient by roughly 0.5.
"""

    amr_path = DATA / "adult_mortality_gradients.csv"
    amr = pd.read_csv(amr_path) if amr_path.exists() else None
    if amr is not None:
        n_cens = amr.groupby(["country", "year"]).ngroups
        doc += f"""
## Adult mortality gradients (census household-deaths modules)

Adult mortality by wealth comes from census microdata, not DHS surveys — the
household outlives the deceased and reports the death alongside its assets. The
method, the assets-vs-income validation, and the completeness checks are on the
[adult-mortality method page](docs/methods/adult-mortality.md); the full
per-census table is in
[docs/tables/adult_mortality.md](docs/tables/adult_mortality.md); and the
fallback for unmeasured countries is the
[general gradient](docs/methods/general-gradient.md).

The age pattern — steepest at prime working ages, fading in old age — is the
by-age shape ogcore's `mort_gradient` accepts directly, and it holds in every
one of the {n_cens} censuses measured:

![Adult-mortality tilt by age band and country](figures/fig5_amr_age_profile.png)
"""

    (ROOT / "ANALYSIS.md").write_text(doc)
    print("wrote ANALYSIS.md")

    # --- docs/ pages ---
    if amr is not None:
        write_general_gradient_page(amr)
        print("wrote docs/methods/general-gradient.md")
        write_adult_table_page(amr)
        print("wrote docs/tables/adult_mortality.md")
        countries = write_country_pages(latest, amr, ccm)
        print(f"wrote docs/countries/ ({len(countries)} pages + index)")


if __name__ == "__main__":
    main()
