# /// script
# requires-python = ">=3.10"
# dependencies = ["pandas"]
# ///
"""Regenerate ANALYSIS.md and the README headline table from the data in ../data/.

Keeps every data-derived number in the prose in sync with the CSVs, so the
documentation cannot drift from the data it describes. The narrative is fixed
here; the counts, tilts, and regional tables are computed. Run after the data
or figures change:

    uv run scripts/build_analysis.py

(or just run scripts/refresh.py, which chains data -> figures -> analysis).
"""

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
REGION_ORDER_NOTE = "(single survey)"
NEG = "−"  # true minus sign, matching the rest of the docs


def fmt(x):
    return f"{NEG}{abs(x):.2f}" if x < 0 else f"{x:.2f}"


def load():
    lib = pd.read_csv(DATA / "gradient_library.csv")
    latest = pd.read_csv(DATA / "gradient_library_latest.csv").merge(
        pd.read_csv(DATA / "dhs_regions.csv"), on="country", how="left"
    )
    return lib, latest


def headline(latest, ind):
    l = latest[latest["indicator"] == ind]
    return {
        "n": l["country"].nunique(),
        "med": l["slope"].median(),
        "q25": l["slope"].quantile(0.25),
        "q75": l["slope"].quantile(0.75),
        "ratio": l["ratio"].median(),
    }


def region_table(latest, ind):
    l = latest[latest["indicator"] == ind]
    g = (
        l.groupby("region")
        .agg(
            n=("country", "nunique"),
            med=("slope", "median"),
            q25=("slope", lambda s: s.quantile(0.25)),
            q75=("slope", lambda s: s.quantile(0.75)),
            ratio=("ratio", "median"),
        )
        .sort_values("med")
    )
    rows = []
    for rgn, r in g.iterrows():
        iqr = REGION_ORDER_NOTE if r["n"] == 1 else f"{fmt(r['q25'])} to {fmt(r['q75'])}"
        rows.append(
            f"| {rgn} | {int(r['n'])} | {fmt(r['med'])} | {iqr} | {r['ratio']:.2f} |"
        )
    return "\n".join(rows)


def sa(latest, ind):
    row = latest[(latest["indicator"] == ind) & (latest["country"] == "South Africa")]
    if not len(row):
        return None
    return {"slope": row["slope"].iloc[0], "ratio": row["ratio"].iloc[0], "year": int(row["year"].iloc[0])}


def replace_between(text, start, end, new):
    a, b = text.index(start) + len(start), text.index(end)
    return text[:a] + "\n" + new + "\n" + text[b:]


def main():
    lib, latest = load()
    tfr, u5 = headline(latest, "TFR"), headline(latest, "U5MR")
    n_surveys = len(lib)
    n_countries = latest["country"].nunique()

    # --- README headline table (between markers) ---
    readme_path = ROOT / "README.md"
    readme = readme_path.read_text()
    table = (
        "| Margin | Countries | Median tilt | IQR | Median poorest/richest ratio |\n"
        "|---|---|---|---|---|\n"
        f"| Fertility (TFR) | {tfr['n']} | **{fmt(tfr['med'])}** | "
        f"{fmt(tfr['q25'])} to {fmt(tfr['q75'])} | {tfr['ratio']:.2f} |\n"
        f"| Under-5 mortality | {u5['n']} | **{fmt(u5['med'])}** | "
        f"{fmt(u5['q25'])} to {fmt(u5['q75'])} | {u5['ratio']:.2f} |"
    )
    readme = replace_between(
        readme,
        "<!-- AUTO-GENERATED by scripts/build_analysis.py — do not edit by hand -->",
        "<!-- END AUTO-GENERATED -->",
        table,
    )
    readme_path.write_text(readme)
    print(f"updated README headline table ({n_surveys} surveys, {n_countries} countries)")

    # --- ANALYSIS.md (fully generated) ---
    sa_t, sa_u = sa(latest, "TFR"), sa(latest, "U5MR")
    doc = f"""# The gradient library, in figures

Documentation of the data in this repo. **This file is generated** by
[`scripts/build_analysis.py`](scripts/build_analysis.py) from the CSVs in
[`data/`](data/); every number below is computed from the data, not hand-typed,
so it cannot drift. Figures come from
[`scripts/make_figures.py`](scripts/make_figures.py) and live in
[`figures/`](figures/). Regenerate both with `uv run scripts/refresh.py`.

South Africa is highlighted throughout as the worked example; pass
`--highlight "<country>"` to `make_figures.py` to feature any other.

The **tilt** summarizing each survey is the OLS slope of ln(rate) on wealth-rank
percentile midpoints (quintiles at the 10th…90th percentile) — the same log scale
OG-Core's income-group demographics consume. Negative means the poor have higher
rates; a tilt of {fmt(tfr['med'])} puts the poorest decile's rate at about
e^({abs(tfr['med']):.2f}×0.8) ≈ {2.718281828 ** (abs(tfr['med']) * 0.8):.1f}× the richest decile's.

Coverage: **{n_surveys} surveys with complete wealth quintets across
{n_countries} countries** (most recent survey per country used for the library
view below).

## Every country, individually

Nearly every line slopes down: the wealth gradient in fertility is close to
universal. South Africa is both low-fertility and mild-gradient (tilt
{fmt(sa_t['slope'])} in {sa_t['year']}, vs the pooled median of {fmt(tfr['med'])}).

![Fertility (TFR) by household wealth rank, one line per country](figures/fig1_tfr_gradients.png)

The same universal direction holds for child mortality, with wider spread across
countries. South Africa's non-monotonic top quintiles reflect the small
child-mortality samples in its {sa_u['year']} survey.

![Under-5 mortality by household wealth rank, one line per country](figures/fig2_u5mr_gradients.png)

## Grouped by region

Each dot is a country's most recent survey; the bar marks the regional
interquartile range and the tick marks the median. Latin America has the steepest
gradients; Sub-Saharan Africa sits mid-range; South Africa is milder than its
region's median on fertility.

![Distribution of gradient tilts by region](figures/fig3_slopes_by_region.png)

**Fertility (TFR) tilt by region**

| Region | Countries | Median tilt | IQR | Median poorest/richest ratio |
|---|---|---|---|---|
{region_table(latest, "TFR")}

**Under-5 mortality tilt by region**

| Region | Countries | Median tilt | IQR | Median poorest/richest ratio |
|---|---|---|---|---|
{region_table(latest, "U5MR")}

## Stability over survey years

All {n_surveys} surveys plotted by fieldwork year, with a rolling median. The
pooled gradient is nearly flat across three and a half decades — wealth gradients
are a stable structural feature, not an eroding one, so a borrowed gradient is not
a decaying quantity. South Africa's own fertility gradient flattened between its
1998 and {sa_t['year']} surveys.

![Gradient tilts across survey years](figures/fig4_slopes_over_time.png)
"""
    (ROOT / "ANALYSIS.md").write_text(doc)
    print("wrote ANALYSIS.md")


if __name__ == "__main__":
    main()
